### ISSUE TITLE
veraltete typo3/cms-composer-installers Version?

### ISSUE THREAD

**Issue by hannesbochmann** [DMKEBUSINESSGMBH/typo3-composer-webroot#3]
@rengaw83 
Momentan wird typo3/cms-composer-installers als "1.2.2 as 1.1.4" installiert. Das scheint mir veraltet. Ich vermute es gab mal in der Version 1.1.4 ein Problem mit dem eigenen Pfad zum htdocs Ordner. Soweit ich das aber sehe wurde das mittlerweile in cms-composer-installers gefixed. Wir müssen die Version also nicht mehr anpassen da der Core selbstz die aktuellste Version nutzt.
Einwände?

**Comment by hannesbochmann** [comment]
@rengaw83 ping

**Comment by rengaw83** [comment]
nein, das ist weiterhin wichtig fuer typo3 6.x projekte.
als dependency ist typo3/cms-composer-installers: >1.1.4,<1.3.0 eingetragen.
Die moeglichkeit den docroot zu setzen geht erst ab cms-composer-installer: 1.2.2

**Comment by hannesbochmann** [comment]
Genau, das meine ich. Mittlerweile wird mind. cms-composer-installer 1.2.7 von TYPO3 6.2.x installiert. Damit kann das dann raus.

**Comment by rengaw83** [comment]
Aber aufpassen, das  ist erst ab TYPO3 6.2.20 so!
