### ISSUE TITLE
default path for imagemagick / graphicsmagick should be used

### ISSUE THREAD

**Issue by mario-seidel** [DMKEBUSINESSGMBH/typo3-composer-webroot#4]
Better leave empty or set default path (/usr/bin imho) here:
https://github.com/DMKEBUSINESSGMBH/typo3-composer-webroot/blob/typo3-87/htdocs/typo3conf/LocalConfiguration.php.sic#L75

**Comment by rengaw83** [comment]
The *.sic only was an backup of the config and should not be committed.
Backups has been removed in 25e6355edfedd58911521acfa45997b88314494f.
